version: "3.7"

services:
  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - my-network
    ports:
      - "${PHPMYADMIN_HOST_PORT}:${PHPMYADMIN_CONTAINER_PORT}"
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}

networks:
  my-network:

volumes:
  db-data: {}
